name: Deploy ML

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy on Server
        run: |
          echo "Deploying ML..."

          cd ~/Factory_System_mvp

          git pull origin main

          cd ml

          source venv/bin/activate

          pip install -r requirements.txt

          sudo systemctl restart ml

          echo "Deployment complete 🚀"